language: java

os:
  - linux

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7


before_install:
  - "[[ -f $HOME/cache/$CONTAINER_ZIP ]] || wget $URL -P $HOME/cache"

script:
  - mvn checkstyle:check
  - mvn clean test -DskipTests=false -Dkaraf.url=file://$HOME/cache/$CONTAINER_ZIP

env:
  - URL="http://www.eu.apache.org/dist/karaf/4.0.2/apache-karaf-4.0.2.zip"
    CONTAINER_ZIP="apache-karaf-4.0.2.zip"

cache:
  directories:
  - $HOME/cache
  - $HOME/.m2
